### ISSUE TITLE
M1: node-cron v3.0 is lacking ScheduledTask.destroy()...

### ISSUE THREAD

**Issue by neallithic64** [neallithic64/capstn-mmchd#205]
as mentioned in countless of issues in the repository, the `destroy()` method is somehow gone
- https://github.com/node-cron/node-cron/issues/269
- https://github.com/node-cron/node-cron/issues/272
- https://github.com/node-cron/node-cron/issues/343
- https://github.com/node-cron/node-cron/issues/348

consequently, a user suggested using `stop()` instead:
> I'm using the "stop" method and manually delete the schedules.
> https://github.com/node-cron/node-cron/issues/269#issuecomment-817643987

this is a really weird bug...

**Comment by sanchitd5** [comment]
+1

**Comment by neallithic64** [comment]
i'll sign this issue off first, since it's been resolved for the meantime
